### PR TITLE
Create audit-spreadsheet

### PR DESCRIPTION
**Pull request by ernee**
Spreadsheet for collaboration

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Thanks so much for this @ernee :)

Definitely think a spreadsheet is a good idea to have more ideas consolidated before PRs are submitted! Instead of committing the URL to the repository, would you be okay with changing the README up a bit and providing the link there instead?

**Comment by ernee** [comment]
Sure thing @housseindjirdeh !

I was curious if the scope of the project was just the secondary description? In the spreadsheet, I also added fields for WordPress-specific suggestions for the title and the main description of the audit.

**Comment by ernee** [comment]
Thanks @housseindjirdeh !

In the experience of myself and colleagues who provide support to WordPress users on performance using the WP Rocket plugin, WordPress users of all skill levels refer to Lighthouse to measure the performance and areas for improvement of their site. It would be useful for them to have language that is accessible for the non-technical and specific to the WordPress environment.

**Comment by ernee** [comment]
To add, there was a discussion at WCUS contributor day regarding the variety of ways WordPress users could address/ fix the recommendations. There is often more than one way to address them, so perhaps a secondary description could provide those options.

**Comment by housseindjirdeh** [comment]
Yep, I definitely see how modifying titles and the main descriptions can make the entire report more digestible for folks who aren't very technical to begin with. The problem here is that it can make things significantly more complicated for an initial prototype. Also, most audit titles _should_ be basic enough that it should carry forward to any tool/framework behind a particular site. Instead of changing the core messaging, we're hoping to just extend it.

Always open to chatting more about this in the near future however, but I hope that makes sense. 

With regards to a Slack group or something similar, definitely a great idea :). Will look into if I can set something up (if folks would like a room to chat before going straight to updating the spreadsheet).

**Comment by ernee** [comment]
Thanks for providing this context @housseindjirdeh! Further discussion with the community would be great and valuable! Thanks for setting this up.

**Comment by housseindjirdeh** [comment]
Simplified the spreadsheet to just have `Title`, `Description` and `WordPress Description` for now. I hope that's okay! We can definitely explore consolidating secondary titles and descriptions in the near future if that functionality gets built into core.

**Comment by housseindjirdeh** [comment]
Closing this PR since we have a link on the README. Could you make the spreadsheet `comment-only` by the shareable link when you get the chance? Will definitely be safer once many people start contributing :)

We're planning to share some external comms about the feature to reach out to more folks in the WordPress community. Will keep you posted when we do! I'll spin up a Slack instance for everyone to collaborate as well.

**Comment by ernee** [comment]
Sounds good @housseindjirdeh ! 

I've updated the spreadsheet to` comment-only`. Thanks for the update on the scope too. Perhaps UX tweaks could be explored as well to help WP users see the specific descriptions sooner (maybe related to the questions raised in #3  ). Looking forward to further collab :)

**Comment by ernee** [comment]
Awesome to see audits live in Lighthouse and PageSpeed Insights! Given the updates mentioned [here](https://github.com/GoogleChrome/lighthouse-stack-packs/blob/master/CONTRIBUTING.md) to submit PRs for changes to the audit strings, are existing spreadsheet (and potentially future) comments being considered or should the respective contributors (who haven’t already submitted PRs) be encouraged to submit PRs now?

**Pull request closed without merging**
